### ISSUE TITLE
New gradient feature - issues

### ISSUE THREAD

**Issue by Bodmer** [Bodmer/TFT_eFEX#11]
The new gradient feature has some issues with rendering in the example.

Please do not raise any issues on this new feature until it is fixed.

Thanks.

**Comment by tobozo** [comment]
sorry about the lack of testing, I hope this is fixed with #12

**Comment by Bodmer** [comment]
I am still getting issues with the example and missing parts. I do not have time to debug this so I have reverted the change.

@tobozo:   Thanks for your contribution. When you have managed to fix the fringing and missing areas, (possibly just a problem with  the example) then I will merge again.
